/**
 * @author Xiao Biqiang
 * @time   2017/5/16
 * @brief  此文件用于确定棋盘的配置，例如坐标，格数等
 */
package com.config;

import java.awt.Point;

public final class ChessboardConfig {
	public static final int CHESSBOARD_WIDTH = 900;
	public static final int CHESSBOARD_HEIGHT = 700;
	
	public static final int HORLINES_NUM = 21;
	public static final int VERLINES_NUM = 21;
	
	//线条间的间隔
	public static final int INTERVAL = 30;
	
	//棋盘左上角的坐标
	public static final int LTX = 50;
	public static final int LTY = 50;
	
	public static final int RTX = 650;
	public static final int RTY = 50;
	
	public static final int RBX = 650;
	public static final int RBY = 650;
	
	public static final int LBX = 50;
	public static final int LBY = 650;
	//棋盘交叉点的坐标
	public static final Point[][] CHESSBOARD_POINTS = {
			{
				new Point(LTX+INTERVAL*0, LTY+INTERVAL*0), new Point(LTX+INTERVAL*1, LTY+INTERVAL*0), new Point(LTX+INTERVAL*2, LTY+INTERVAL*0), new Point(LTX+INTERVAL*3, LTY+INTERVAL*0), new Point(LTX+INTERVAL*4, LTY+INTERVAL*0), 
			    new Point(LTX+INTERVAL*5, LTY+INTERVAL*0), new Point(LTX+INTERVAL*6, LTY+INTERVAL*0), new Point(LTX+INTERVAL*7, LTY+INTERVAL*0), new Point(LTX+INTERVAL*8, LTY+INTERVAL*0), new Point(LTX+INTERVAL*9, LTY+INTERVAL*0),
			    new Point(LTX+INTERVAL*10, LTY+INTERVAL*0), new Point(LTX+INTERVAL*11, LTY+INTERVAL*0), new Point(LTX+INTERVAL*12, LTY+INTERVAL*0), new Point(LTX+INTERVAL*13, LTY+INTERVAL*0), new Point(LTX+INTERVAL*14, LTY+INTERVAL*0),
			    new Point(LTX+INTERVAL*15, LTY+INTERVAL*0), new Point(LTX+INTERVAL*16, LTY+INTERVAL*0), new Point(LTX+INTERVAL*17, LTY+INTERVAL*0), new Point(LTX+INTERVAL*18, LTY+INTERVAL*0), new Point(LTX+INTERVAL*19, LTY+INTERVAL*0), 
			    new Point(LTX+INTERVAL*20, LTY+INTERVAL*0)
			},
			{
				new Point(LTX+INTERVAL*0, LTY+INTERVAL*1), new Point(LTX+INTERVAL*1, LTY+INTERVAL*1), new Point(LTX+INTERVAL*2, LTY+INTERVAL*1), new Point(LTX+INTERVAL*3, LTY+INTERVAL*1), new Point(LTX+INTERVAL*4, LTY+INTERVAL*1), 
			    new Point(LTX+INTERVAL*5, LTY+INTERVAL*1), new Point(LTX+INTERVAL*6, LTY+INTERVAL*1), new Point(LTX+INTERVAL*7, LTY+INTERVAL*1), new Point(LTX+INTERVAL*8, LTY+INTERVAL*1), new Point(LTX+INTERVAL*9, LTY+INTERVAL*1),
			    new Point(LTX+INTERVAL*10, LTY+INTERVAL*1), new Point(LTX+INTERVAL*11, LTY+INTERVAL*1), new Point(LTX+INTERVAL*12, LTY+INTERVAL*1), new Point(LTX+INTERVAL*13, LTY+INTERVAL*1), new Point(LTX+INTERVAL*14, LTY+INTERVAL*1),
			    new Point(LTX+INTERVAL*15, LTY+INTERVAL*1), new Point(LTX+INTERVAL*16, LTY+INTERVAL*1), new Point(LTX+INTERVAL*17, LTY+INTERVAL*1), new Point(LTX+INTERVAL*18, LTY+INTERVAL*1), new Point(LTX+INTERVAL*19, LTY+INTERVAL*1), 
			    new Point(LTX+INTERVAL*20, LTY+INTERVAL*1)
			},
			{
				new Point(LTX+INTERVAL*0, LTY+INTERVAL*2), new Point(LTX+INTERVAL*1, LTY+INTERVAL*2), new Point(LTX+INTERVAL*2, LTY+INTERVAL*2), new Point(LTX+INTERVAL*3, LTY+INTERVAL*2), new Point(LTX+INTERVAL*4, LTY+INTERVAL*2), 
			    new Point(LTX+INTERVAL*5, LTY+INTERVAL*2), new Point(LTX+INTERVAL*6, LTY+INTERVAL*2), new Point(LTX+INTERVAL*7, LTY+INTERVAL*2), new Point(LTX+INTERVAL*8, LTY+INTERVAL*2), new Point(LTX+INTERVAL*9, LTY+INTERVAL*2),
			    new Point(LTX+INTERVAL*10, LTY+INTERVAL*2), new Point(LTX+INTERVAL*11, LTY+INTERVAL*2), new Point(LTX+INTERVAL*12, LTY+INTERVAL*2), new Point(LTX+INTERVAL*13, LTY+INTERVAL*2), new Point(LTX+INTERVAL*14, LTY+INTERVAL*2),
			    new Point(LTX+INTERVAL*15, LTY+INTERVAL*2), new Point(LTX+INTERVAL*16, LTY+INTERVAL*2), new Point(LTX+INTERVAL*17, LTY+INTERVAL*2), new Point(LTX+INTERVAL*18, LTY+INTERVAL*2), new Point(LTX+INTERVAL*19, LTY+INTERVAL*2), 
			    new Point(LTX+INTERVAL*20, LTY+INTERVAL*2)
			},
			{
				new Point(LTX+INTERVAL*0, LTY+INTERVAL*3), new Point(LTX+INTERVAL*1, LTY+INTERVAL*3), new Point(LTX+INTERVAL*2, LTY+INTERVAL*3), new Point(LTX+INTERVAL*3, LTY+INTERVAL*3), new Point(LTX+INTERVAL*4, LTY+INTERVAL*3), 
			    new Point(LTX+INTERVAL*5, LTY+INTERVAL*3), new Point(LTX+INTERVAL*6, LTY+INTERVAL*3), new Point(LTX+INTERVAL*7, LTY+INTERVAL*3), new Point(LTX+INTERVAL*8, LTY+INTERVAL*3), new Point(LTX+INTERVAL*9, LTY+INTERVAL*3),
			    new Point(LTX+INTERVAL*10, LTY+INTERVAL*3), new Point(LTX+INTERVAL*11, LTY+INTERVAL*3), new Point(LTX+INTERVAL*12, LTY+INTERVAL*3), new Point(LTX+INTERVAL*13, LTY+INTERVAL*3), new Point(LTX+INTERVAL*14, LTY+INTERVAL*3),
			    new Point(LTX+INTERVAL*15, LTY+INTERVAL*3), new Point(LTX+INTERVAL*16, LTY+INTERVAL*3), new Point(LTX+INTERVAL*17, LTY+INTERVAL*3), new Point(LTX+INTERVAL*18, LTY+INTERVAL*3), new Point(LTX+INTERVAL*19, LTY+INTERVAL*3), 
			    new Point(LTX+INTERVAL*20, LTY+INTERVAL*3)
			},
			{
				new Point(LTX+INTERVAL*0, LTY+INTERVAL*4), new Point(LTX+INTERVAL*1, LTY+INTERVAL*4), new Point(LTX+INTERVAL*2, LTY+INTERVAL*4), new Point(LTX+INTERVAL*3, LTY+INTERVAL*4), new Point(LTX+INTERVAL*4, LTY+INTERVAL*4), 
			    new Point(LTX+INTERVAL*5, LTY+INTERVAL*4), new Point(LTX+INTERVAL*6, LTY+INTERVAL*4), new Point(LTX+INTERVAL*7, LTY+INTERVAL*4), new Point(LTX+INTERVAL*8, LTY+INTERVAL*4), new Point(LTX+INTERVAL*9, LTY+INTERVAL*4),
			    new Point(LTX+INTERVAL*10, LTY+INTERVAL*4), new Point(LTX+INTERVAL*11, LTY+INTERVAL*4), new Point(LTX+INTERVAL*12, LTY+INTERVAL*4), new Point(LTX+INTERVAL*13, LTY+INTERVAL*4), new Point(LTX+INTERVAL*14, LTY+INTERVAL*4),
			    new Point(LTX+INTERVAL*15, LTY+INTERVAL*4), new Point(LTX+INTERVAL*16, LTY+INTERVAL*4), new Point(LTX+INTERVAL*17, LTY+INTERVAL*4), new Point(LTX+INTERVAL*18, LTY+INTERVAL*4), new Point(LTX+INTERVAL*19, LTY+INTERVAL*4), 
			    new Point(LTX+INTERVAL*20, LTY+INTERVAL*4)
			},
			{
				new Point(LTX+INTERVAL*0, LTY+INTERVAL*5), new Point(LTX+INTERVAL*1, LTY+INTERVAL*5), new Point(LTX+INTERVAL*2, LTY+INTERVAL*5), new Point(LTX+INTERVAL*3, LTY+INTERVAL*5), new Point(LTX+INTERVAL*4, LTY+INTERVAL*5), 
			    new Point(LTX+INTERVAL*5, LTY+INTERVAL*5), new Point(LTX+INTERVAL*6, LTY+INTERVAL*5), new Point(LTX+INTERVAL*7, LTY+INTERVAL*5), new Point(LTX+INTERVAL*8, LTY+INTERVAL*5), new Point(LTX+INTERVAL*9, LTY+INTERVAL*5),
			    new Point(LTX+INTERVAL*10, LTY+INTERVAL*5), new Point(LTX+INTERVAL*11, LTY+INTERVAL*5), new Point(LTX+INTERVAL*12, LTY+INTERVAL*5), new Point(LTX+INTERVAL*13, LTY+INTERVAL*5), new Point(LTX+INTERVAL*14, LTY+INTERVAL*5),
			    new Point(LTX+INTERVAL*15, LTY+INTERVAL*5), new Point(LTX+INTERVAL*16, LTY+INTERVAL*5), new Point(LTX+INTERVAL*17, LTY+INTERVAL*5), new Point(LTX+INTERVAL*18, LTY+INTERVAL*5), new Point(LTX+INTERVAL*19, LTY+INTERVAL*5), 
			    new Point(LTX+INTERVAL*20, LTY+INTERVAL*5)
			},
			{
				new Point(LTX+INTERVAL*0, LTY+INTERVAL*6), new Point(LTX+INTERVAL*1, LTY+INTERVAL*6), new Point(LTX+INTERVAL*2, LTY+INTERVAL*6), new Point(LTX+INTERVAL*3, LTY+INTERVAL*6), new Point(LTX+INTERVAL*4, LTY+INTERVAL*6), 
			    new Point(LTX+INTERVAL*5, LTY+INTERVAL*6), new Point(LTX+INTERVAL*6, LTY+INTERVAL*6), new Point(LTX+INTERVAL*7, LTY+INTERVAL*6), new Point(LTX+INTERVAL*8, LTY+INTERVAL*6), new Point(LTX+INTERVAL*9, LTY+INTERVAL*6),
			    new Point(LTX+INTERVAL*10, LTY+INTERVAL*6), new Point(LTX+INTERVAL*11, LTY+INTERVAL*6), new Point(LTX+INTERVAL*12, LTY+INTERVAL*6), new Point(LTX+INTERVAL*13, LTY+INTERVAL*6), new Point(LTX+INTERVAL*14, LTY+INTERVAL*6),
			    new Point(LTX+INTERVAL*15, LTY+INTERVAL*6), new Point(LTX+INTERVAL*16, LTY+INTERVAL*6), new Point(LTX+INTERVAL*17, LTY+INTERVAL*6), new Point(LTX+INTERVAL*18, LTY+INTERVAL*6), new Point(LTX+INTERVAL*19, LTY+INTERVAL*6), 
			    new Point(LTX+INTERVAL*20, LTY+INTERVAL*6)
			},
			{
				new Point(LTX+INTERVAL*0, LTY+INTERVAL*7), new Point(LTX+INTERVAL*1, LTY+INTERVAL*7), new Point(LTX+INTERVAL*2, LTY+INTERVAL*7), new Point(LTX+INTERVAL*3, LTY+INTERVAL*7), new Point(LTX+INTERVAL*4, LTY+INTERVAL*7), 
			    new Point(LTX+INTERVAL*5, LTY+INTERVAL*7), new Point(LTX+INTERVAL*6, LTY+INTERVAL*7), new Point(LTX+INTERVAL*7, LTY+INTERVAL*7), new Point(LTX+INTERVAL*8, LTY+INTERVAL*7), new Point(LTX+INTERVAL*9, LTY+INTERVAL*7),
			    new Point(LTX+INTERVAL*10, LTY+INTERVAL*7), new Point(LTX+INTERVAL*11, LTY+INTERVAL*7), new Point(LTX+INTERVAL*12, LTY+INTERVAL*7), new Point(LTX+INTERVAL*13, LTY+INTERVAL*7), new Point(LTX+INTERVAL*14, LTY+INTERVAL*7),
			    new Point(LTX+INTERVAL*15, LTY+INTERVAL*7), new Point(LTX+INTERVAL*16, LTY+INTERVAL*7), new Point(LTX+INTERVAL*17, LTY+INTERVAL*7), new Point(LTX+INTERVAL*18, LTY+INTERVAL*7), new Point(LTX+INTERVAL*19, LTY+INTERVAL*7), 
			    new Point(LTX+INTERVAL*20, LTY+INTERVAL*7)
			},
			{
				new Point(LTX+INTERVAL*0, LTY+INTERVAL*8), new Point(LTX+INTERVAL*1, LTY+INTERVAL*8), new Point(LTX+INTERVAL*2, LTY+INTERVAL*8), new Point(LTX+INTERVAL*3, LTY+INTERVAL*8), new Point(LTX+INTERVAL*4, LTY+INTERVAL*8), 
			    new Point(LTX+INTERVAL*5, LTY+INTERVAL*8), new Point(LTX+INTERVAL*6, LTY+INTERVAL*8), new Point(LTX+INTERVAL*7, LTY+INTERVAL*8), new Point(LTX+INTERVAL*8, LTY+INTERVAL*8), new Point(LTX+INTERVAL*9, LTY+INTERVAL*8),
			    new Point(LTX+INTERVAL*10, LTY+INTERVAL*8), new Point(LTX+INTERVAL*11, LTY+INTERVAL*8), new Point(LTX+INTERVAL*12, LTY+INTERVAL*8), new Point(LTX+INTERVAL*13, LTY+INTERVAL*8), new Point(LTX+INTERVAL*14, LTY+INTERVAL*8),
			    new Point(LTX+INTERVAL*15, LTY+INTERVAL*8), new Point(LTX+INTERVAL*16, LTY+INTERVAL*8), new Point(LTX+INTERVAL*17, LTY+INTERVAL*8), new Point(LTX+INTERVAL*18, LTY+INTERVAL*8), new Point(LTX+INTERVAL*19, LTY+INTERVAL*8), 
			    new Point(LTX+INTERVAL*20, LTY+INTERVAL*8)
			},
			{
				new Point(LTX+INTERVAL*0, LTY+INTERVAL*9), new Point(LTX+INTERVAL*1, LTY+INTERVAL*9), new Point(LTX+INTERVAL*2, LTY+INTERVAL*9), new Point(LTX+INTERVAL*3, LTY+INTERVAL*9), new Point(LTX+INTERVAL*4, LTY+INTERVAL*9), 
			    new Point(LTX+INTERVAL*5, LTY+INTERVAL*9), new Point(LTX+INTERVAL*6, LTY+INTERVAL*9), new Point(LTX+INTERVAL*7, LTY+INTERVAL*9), new Point(LTX+INTERVAL*8, LTY+INTERVAL*9), new Point(LTX+INTERVAL*9, LTY+INTERVAL*9),
			    new Point(LTX+INTERVAL*10, LTY+INTERVAL*9), new Point(LTX+INTERVAL*11, LTY+INTERVAL*9), new Point(LTX+INTERVAL*12, LTY+INTERVAL*9), new Point(LTX+INTERVAL*13, LTY+INTERVAL*9), new Point(LTX+INTERVAL*14, LTY+INTERVAL*9),
			    new Point(LTX+INTERVAL*15, LTY+INTERVAL*9), new Point(LTX+INTERVAL*16, LTY+INTERVAL*9), new Point(LTX+INTERVAL*17, LTY+INTERVAL*9), new Point(LTX+INTERVAL*18, LTY+INTERVAL*9), new Point(LTX+INTERVAL*19, LTY+INTERVAL*9), 
			    new Point(LTX+INTERVAL*20, LTY+INTERVAL*9)
			},
			{
				new Point(LTX+INTERVAL*0, LTY+INTERVAL*10), new Point(LTX+INTERVAL*1, LTY+INTERVAL*10), new Point(LTX+INTERVAL*2, LTY+INTERVAL*10), new Point(LTX+INTERVAL*3, LTY+INTERVAL*10), new Point(LTX+INTERVAL*4, LTY+INTERVAL*10), 
			    new Point(LTX+INTERVAL*5, LTY+INTERVAL*10), new Point(LTX+INTERVAL*6, LTY+INTERVAL*10), new Point(LTX+INTERVAL*7, LTY+INTERVAL*10), new Point(LTX+INTERVAL*8, LTY+INTERVAL*10), new Point(LTX+INTERVAL*9, LTY+INTERVAL*10),
			    new Point(LTX+INTERVAL*10, LTY+INTERVAL*10), new Point(LTX+INTERVAL*11, LTY+INTERVAL*10), new Point(LTX+INTERVAL*12, LTY+INTERVAL*10), new Point(LTX+INTERVAL*13, LTY+INTERVAL*10), new Point(LTX+INTERVAL*14, LTY+INTERVAL*10),
			    new Point(LTX+INTERVAL*15, LTY+INTERVAL*10), new Point(LTX+INTERVAL*16, LTY+INTERVAL*10), new Point(LTX+INTERVAL*17, LTY+INTERVAL*10), new Point(LTX+INTERVAL*18, LTY+INTERVAL*10), new Point(LTX+INTERVAL*19, LTY+INTERVAL*10), 
			    new Point(LTX+INTERVAL*20, LTY+INTERVAL*10)
			},
			{
				new Point(LTX+INTERVAL*0, LTY+INTERVAL*11), new Point(LTX+INTERVAL*1, LTY+INTERVAL*11), new Point(LTX+INTERVAL*2, LTY+INTERVAL*11), new Point(LTX+INTERVAL*3, LTY+INTERVAL*11), new Point(LTX+INTERVAL*4, LTY+INTERVAL*11), 
			    new Point(LTX+INTERVAL*5, LTY+INTERVAL*11), new Point(LTX+INTERVAL*6, LTY+INTERVAL*11), new Point(LTX+INTERVAL*7, LTY+INTERVAL*11), new Point(LTX+INTERVAL*8, LTY+INTERVAL*11), new Point(LTX+INTERVAL*9, LTY+INTERVAL*11),
			    new Point(LTX+INTERVAL*10, LTY+INTERVAL*11), new Point(LTX+INTERVAL*11, LTY+INTERVAL*11), new Point(LTX+INTERVAL*12, LTY+INTERVAL*11), new Point(LTX+INTERVAL*13, LTY+INTERVAL*11), new Point(LTX+INTERVAL*14, LTY+INTERVAL*11),
			    new Point(LTX+INTERVAL*15, LTY+INTERVAL*11), new Point(LTX+INTERVAL*16, LTY+INTERVAL*11), new Point(LTX+INTERVAL*17, LTY+INTERVAL*11), new Point(LTX+INTERVAL*18, LTY+INTERVAL*11), new Point(LTX+INTERVAL*19, LTY+INTERVAL*11), 
			    new Point(LTX+INTERVAL*20, LTY+INTERVAL*11)
			},
			{
				new Point(LTX+INTERVAL*0, LTY+INTERVAL*12), new Point(LTX+INTERVAL*1, LTY+INTERVAL*12), new Point(LTX+INTERVAL*2, LTY+INTERVAL*12), new Point(LTX+INTERVAL*3, LTY+INTERVAL*12), new Point(LTX+INTERVAL*4, LTY+INTERVAL*12), 
			    new Point(LTX+INTERVAL*5, LTY+INTERVAL*12), new Point(LTX+INTERVAL*6, LTY+INTERVAL*12), new Point(LTX+INTERVAL*7, LTY+INTERVAL*12), new Point(LTX+INTERVAL*8, LTY+INTERVAL*12), new Point(LTX+INTERVAL*9, LTY+INTERVAL*12),
			    new Point(LTX+INTERVAL*10, LTY+INTERVAL*12), new Point(LTX+INTERVAL*11, LTY+INTERVAL*12), new Point(LTX+INTERVAL*12, LTY+INTERVAL*12), new Point(LTX+INTERVAL*13, LTY+INTERVAL*12), new Point(LTX+INTERVAL*14, LTY+INTERVAL*12),
			    new Point(LTX+INTERVAL*15, LTY+INTERVAL*12), new Point(LTX+INTERVAL*16, LTY+INTERVAL*12), new Point(LTX+INTERVAL*17, LTY+INTERVAL*12), new Point(LTX+INTERVAL*18, LTY+INTERVAL*12), new Point(LTX+INTERVAL*19, LTY+INTERVAL*12), 
			    new Point(LTX+INTERVAL*20, LTY+INTERVAL*12)
			},
			{
				new Point(LTX+INTERVAL*0, LTY+INTERVAL*13), new Point(LTX+INTERVAL*1, LTY+INTERVAL*13), new Point(LTX+INTERVAL*2, LTY+INTERVAL*13), new Point(LTX+INTERVAL*3, LTY+INTERVAL*13), new Point(LTX+INTERVAL*4, LTY+INTERVAL*13), 
			    new Point(LTX+INTERVAL*5, LTY+INTERVAL*13), new Point(LTX+INTERVAL*6, LTY+INTERVAL*13), new Point(LTX+INTERVAL*7, LTY+INTERVAL*13), new Point(LTX+INTERVAL*8, LTY+INTERVAL*13), new Point(LTX+INTERVAL*9, LTY+INTERVAL*13),
			    new Point(LTX+INTERVAL*10, LTY+INTERVAL*13), new Point(LTX+INTERVAL*11, LTY+INTERVAL*13), new Point(LTX+INTERVAL*12, LTY+INTERVAL*13), new Point(LTX+INTERVAL*13, LTY+INTERVAL*13), new Point(LTX+INTERVAL*14, LTY+INTERVAL*13),
			    new Point(LTX+INTERVAL*15, LTY+INTERVAL*13), new Point(LTX+INTERVAL*16, LTY+INTERVAL*13), new Point(LTX+INTERVAL*17, LTY+INTERVAL*13), new Point(LTX+INTERVAL*18, LTY+INTERVAL*13), new Point(LTX+INTERVAL*19, LTY+INTERVAL*13), 
			    new Point(LTX+INTERVAL*20, LTY+INTERVAL*13)
			},
			{
				new Point(LTX+INTERVAL*0, LTY+INTERVAL*14), new Point(LTX+INTERVAL*1, LTY+INTERVAL*14), new Point(LTX+INTERVAL*2, LTY+INTERVAL*14), new Point(LTX+INTERVAL*3, LTY+INTERVAL*14), new Point(LTX+INTERVAL*4, LTY+INTERVAL*14), 
			    new Point(LTX+INTERVAL*5, LTY+INTERVAL*14), new Point(LTX+INTERVAL*6, LTY+INTERVAL*14), new Point(LTX+INTERVAL*7, LTY+INTERVAL*14), new Point(LTX+INTERVAL*8, LTY+INTERVAL*14), new Point(LTX+INTERVAL*9, LTY+INTERVAL*14),
			    new Point(LTX+INTERVAL*10, LTY+INTERVAL*14), new Point(LTX+INTERVAL*11, LTY+INTERVAL*14), new Point(LTX+INTERVAL*12, LTY+INTERVAL*14), new Point(LTX+INTERVAL*13, LTY+INTERVAL*14), new Point(LTX+INTERVAL*14, LTY+INTERVAL*14),
			    new Point(LTX+INTERVAL*15, LTY+INTERVAL*14), new Point(LTX+INTERVAL*16, LTY+INTERVAL*14), new Point(LTX+INTERVAL*17, LTY+INTERVAL*14), new Point(LTX+INTERVAL*18, LTY+INTERVAL*14), new Point(LTX+INTERVAL*19, LTY+INTERVAL*14), 
			    new Point(LTX+INTERVAL*20, LTY+INTERVAL*14)
			},
			{
				new Point(LTX+INTERVAL*0, LTY+INTERVAL*15), new Point(LTX+INTERVAL*1, LTY+INTERVAL*15), new Point(LTX+INTERVAL*2, LTY+INTERVAL*15), new Point(LTX+INTERVAL*3, LTY+INTERVAL*15), new Point(LTX+INTERVAL*4, LTY+INTERVAL*15), 
			    new Point(LTX+INTERVAL*5, LTY+INTERVAL*15), new Point(LTX+INTERVAL*6, LTY+INTERVAL*15), new Point(LTX+INTERVAL*7, LTY+INTERVAL*15), new Point(LTX+INTERVAL*8, LTY+INTERVAL*15), new Point(LTX+INTERVAL*9, LTY+INTERVAL*15),
			    new Point(LTX+INTERVAL*10, LTY+INTERVAL*15), new Point(LTX+INTERVAL*11, LTY+INTERVAL*15), new Point(LTX+INTERVAL*12, LTY+INTERVAL*15), new Point(LTX+INTERVAL*13, LTY+INTERVAL*15), new Point(LTX+INTERVAL*14, LTY+INTERVAL*15),
			    new Point(LTX+INTERVAL*15, LTY+INTERVAL*15), new Point(LTX+INTERVAL*16, LTY+INTERVAL*15), new Point(LTX+INTERVAL*17, LTY+INTERVAL*15), new Point(LTX+INTERVAL*18, LTY+INTERVAL*15), new Point(LTX+INTERVAL*19, LTY+INTERVAL*15), 
			    new Point(LTX+INTERVAL*20, LTY+INTERVAL*15)
			},
			{
				new Point(LTX+INTERVAL*0, LTY+INTERVAL*16), new Point(LTX+INTERVAL*1, LTY+INTERVAL*16), new Point(LTX+INTERVAL*2, LTY+INTERVAL*16), new Point(LTX+INTERVAL*3, LTY+INTERVAL*16), new Point(LTX+INTERVAL*4, LTY+INTERVAL*16), 
			    new Point(LTX+INTERVAL*5, LTY+INTERVAL*16), new Point(LTX+INTERVAL*6, LTY+INTERVAL*16), new Point(LTX+INTERVAL*7, LTY+INTERVAL*16), new Point(LTX+INTERVAL*8, LTY+INTERVAL*16), new Point(LTX+INTERVAL*9, LTY+INTERVAL*16),
			    new Point(LTX+INTERVAL*10, LTY+INTERVAL*16), new Point(LTX+INTERVAL*11, LTY+INTERVAL*16), new Point(LTX+INTERVAL*12, LTY+INTERVAL*16), new Point(LTX+INTERVAL*13, LTY+INTERVAL*16), new Point(LTX+INTERVAL*14, LTY+INTERVAL*16),
			    new Point(LTX+INTERVAL*15, LTY+INTERVAL*16), new Point(LTX+INTERVAL*16, LTY+INTERVAL*16), new Point(LTX+INTERVAL*17, LTY+INTERVAL*16), new Point(LTX+INTERVAL*18, LTY+INTERVAL*16), new Point(LTX+INTERVAL*19, LTY+INTERVAL*16), 
			    new Point(LTX+INTERVAL*20, LTY+INTERVAL*16)
			},
			{
				new Point(LTX+INTERVAL*0, LTY+INTERVAL*17), new Point(LTX+INTERVAL*1, LTY+INTERVAL*17), new Point(LTX+INTERVAL*2, LTY+INTERVAL*17), new Point(LTX+INTERVAL*3, LTY+INTERVAL*17), new Point(LTX+INTERVAL*4, LTY+INTERVAL*17), 
			    new Point(LTX+INTERVAL*5, LTY+INTERVAL*17), new Point(LTX+INTERVAL*6, LTY+INTERVAL*17), new Point(LTX+INTERVAL*7, LTY+INTERVAL*17), new Point(LTX+INTERVAL*8, LTY+INTERVAL*17), new Point(LTX+INTERVAL*9, LTY+INTERVAL*17),
			    new Point(LTX+INTERVAL*10, LTY+INTERVAL*17), new Point(LTX+INTERVAL*11, LTY+INTERVAL*17), new Point(LTX+INTERVAL*12, LTY+INTERVAL*17), new Point(LTX+INTERVAL*13, LTY+INTERVAL*17), new Point(LTX+INTERVAL*14, LTY+INTERVAL*17),
			    new Point(LTX+INTERVAL*15, LTY+INTERVAL*17), new Point(LTX+INTERVAL*16, LTY+INTERVAL*17), new Point(LTX+INTERVAL*17, LTY+INTERVAL*17), new Point(LTX+INTERVAL*18, LTY+INTERVAL*17), new Point(LTX+INTERVAL*19, LTY+INTERVAL*17), 
			    new Point(LTX+INTERVAL*20, LTY+INTERVAL*17)
			},
			{
				new Point(LTX+INTERVAL*0, LTY+INTERVAL*18), new Point(LTX+INTERVAL*1, LTY+INTERVAL*18), new Point(LTX+INTERVAL*2, LTY+INTERVAL*18), new Point(LTX+INTERVAL*3, LTY+INTERVAL*18), new Point(LTX+INTERVAL*4, LTY+INTERVAL*18), 
			    new Point(LTX+INTERVAL*5, LTY+INTERVAL*18), new Point(LTX+INTERVAL*6, LTY+INTERVAL*18), new Point(LTX+INTERVAL*7, LTY+INTERVAL*18), new Point(LTX+INTERVAL*8, LTY+INTERVAL*18), new Point(LTX+INTERVAL*9, LTY+INTERVAL*18),
			    new Point(LTX+INTERVAL*10, LTY+INTERVAL*18), new Point(LTX+INTERVAL*11, LTY+INTERVAL*18), new Point(LTX+INTERVAL*12, LTY+INTERVAL*18), new Point(LTX+INTERVAL*13, LTY+INTERVAL*18), new Point(LTX+INTERVAL*14, LTY+INTERVAL*18),
			    new Point(LTX+INTERVAL*15, LTY+INTERVAL*18), new Point(LTX+INTERVAL*16, LTY+INTERVAL*18), new Point(LTX+INTERVAL*17, LTY+INTERVAL*18), new Point(LTX+INTERVAL*18, LTY+INTERVAL*18), new Point(LTX+INTERVAL*19, LTY+INTERVAL*18), 
			    new Point(LTX+INTERVAL*20, LTY+INTERVAL*18)
			},
			{
				new Point(LTX+INTERVAL*0, LTY+INTERVAL*19), new Point(LTX+INTERVAL*1, LTY+INTERVAL*19), new Point(LTX+INTERVAL*2, LTY+INTERVAL*19), new Point(LTX+INTERVAL*3, LTY+INTERVAL*19), new Point(LTX+INTERVAL*4, LTY+INTERVAL*19), 
			    new Point(LTX+INTERVAL*5, LTY+INTERVAL*19), new Point(LTX+INTERVAL*6, LTY+INTERVAL*19), new Point(LTX+INTERVAL*7, LTY+INTERVAL*19), new Point(LTX+INTERVAL*8, LTY+INTERVAL*19), new Point(LTX+INTERVAL*9, LTY+INTERVAL*19),
			    new Point(LTX+INTERVAL*10, LTY+INTERVAL*19), new Point(LTX+INTERVAL*11, LTY+INTERVAL*19), new Point(LTX+INTERVAL*12, LTY+INTERVAL*19), new Point(LTX+INTERVAL*13, LTY+INTERVAL*19), new Point(LTX+INTERVAL*14, LTY+INTERVAL*19),
			    new Point(LTX+INTERVAL*15, LTY+INTERVAL*19), new Point(LTX+INTERVAL*16, LTY+INTERVAL*19), new Point(LTX+INTERVAL*17, LTY+INTERVAL*19), new Point(LTX+INTERVAL*18, LTY+INTERVAL*19), new Point(LTX+INTERVAL*19, LTY+INTERVAL*19), 
			    new Point(LTX+INTERVAL*20, LTY+INTERVAL*19)
			},
			{
				new Point(LTX+INTERVAL*0, LTY+INTERVAL*20), new Point(LTX+INTERVAL*1, LTY+INTERVAL*20), new Point(LTX+INTERVAL*2, LTY+INTERVAL*20), new Point(LTX+INTERVAL*3, LTY+INTERVAL*20), new Point(LTX+INTERVAL*4, LTY+INTERVAL*20), 
			    new Point(LTX+INTERVAL*5, LTY+INTERVAL*20), new Point(LTX+INTERVAL*6, LTY+INTERVAL*20), new Point(LTX+INTERVAL*7, LTY+INTERVAL*20), new Point(LTX+INTERVAL*8, LTY+INTERVAL*20), new Point(LTX+INTERVAL*9, LTY+INTERVAL*20),
			    new Point(LTX+INTERVAL*10, LTY+INTERVAL*20), new Point(LTX+INTERVAL*11, LTY+INTERVAL*20), new Point(LTX+INTERVAL*12, LTY+INTERVAL*20), new Point(LTX+INTERVAL*13, LTY+INTERVAL*20), new Point(LTX+INTERVAL*14, LTY+INTERVAL*20),
			    new Point(LTX+INTERVAL*15, LTY+INTERVAL*20), new Point(LTX+INTERVAL*16, LTY+INTERVAL*20), new Point(LTX+INTERVAL*17, LTY+INTERVAL*20), new Point(LTX+INTERVAL*18, LTY+INTERVAL*20), new Point(LTX+INTERVAL*19, LTY+INTERVAL*20), 
			    new Point(LTX+INTERVAL*20, LTY+INTERVAL*20)
			}
		};	
	
	//棋盘外围4个点的坐标
	public static Point[] OUT_CHESSBOARD_POINTS = {new Point(43, 43), new Point(657, 43), new Point(657, 657), new Point(43, 657)};
	
	//5个标致点的坐标
	public static Point[] FLAG_POINTS = {CHESSBOARD_POINTS[10][10], CHESSBOARD_POINTS[3][3], CHESSBOARD_POINTS[3][17], CHESSBOARD_POINTS[17][17], CHESSBOARD_POINTS[17][3]};
	public static int FLAG_POINTS_RADIUS = 5;
}
